platform :ios, '14.0'
use_frameworks!

# Capacitor iOS plugins (managed via `npx cap sync ios` which updates
# the Podfile dependencies from package.json). The blocks below list the
# pods that correspond to the plugins declared in package.json.

target 'App' do
  capacitor_path = '../node_modules/@capacitor/ios'

  pod 'Capacitor', :path => capacitor_path
  pod 'CapacitorCordova', :path => capacitor_path

  pod 'CapacitorApp', :path => '../node_modules/@capacitor/app'
  pod 'CapacitorBrowser', :path => '../node_modules/@capacitor/browser'
  pod 'CapacitorCamera', :path => '../node_modules/@capacitor/camera'
  pod 'CapacitorClipboard', :path => '../node_modules/@capacitor/clipboard'
  pod 'CapacitorDevice', :path => '../node_modules/@capacitor/device'
  pod 'CapacitorFilesystem', :path => '../node_modules/@capacitor/file-system'
  pod 'CapacitorGeolocation', :path => '../node_modules/@capacitor/geolocation'
  pod 'CapacitorHaptics', :path => '../node_modules/@capacitor/haptics'
  pod 'CapacitorLocalNotifications', :path => '../node_modules/@capacitor/local-notifications'
  pod 'CapacitorNetwork', :path => '../node_modules/@capacitor/network'
  pod 'CapacitorPreferences', :path => '../node_modules/@capacitor/preferences'
  pod 'CapacitorPushNotifications', :path => '../node_modules/@capacitor/push-notifications'
  pod 'CapacitorShare', :path => '../node_modules/@capacitor/share'
  pod 'CapacitorSplashScreen', :path => '../node_modules/@capacitor/splash-screen'
  pod 'CapacitorStatusBar', :path => '../node_modules/@capacitor/status-bar'
  pod 'CapacitorToast', :path => '../node_modules/@capacitor/toast'
end
